### ISSUE TITLE
[Tay] Calculate outliers and pass back df and output csv with optional parameters

### ISSUE THREAD

**Issue by sphussey** [jayesh-07/pythonpackage-intelliprocess-DS-5010#12]
Create a function for calculating outliers for each attribute and have it return a df with those outliers removes and also output . The function should take parameters for options to save the df as a csv as well as a filename which is appended with a datetime stamp.

some helpful code i have already:
import datetime

fn(save=True, filename="intelliviz_correlation_matrix_heatmap"):

if save is True:
    timestamp = str(datetime.datetime.now()).replace(" ", "_")
    filename = filename + "_" + timestamp + ".csv"

**Comment by sphussey** [comment]
not sure how to assign this to Tay,  @jayesh-07 do you know how?

**Comment by jayesh-07** [comment]
> not sure how to assign this to Tay, @jayesh-07 do you know how?

When Tay will make a commit a contributor status will be assigned and then you can assign issues.
