### ISSUE TITLE
[Team] Consider PDF output with summary of all plots and things that we do

### ISSUE THREAD

**Issue by sphussey** [jayesh-07/pythonpackage-intelliprocess-DS-5010#15]
Howdyyy, not sure anybody if familiar with python module for creating pdf reports but Tay and I were chatting yesterday about this. Might be nice to summarize everything we are doing into a report output

**Comment by jayesh-07** [comment]
Do you mean running all the functions on the input data set and giving out a report kind of thing?

**Comment by sphussey** [comment]
I think this is out of scope at this time, we can delete this comment
