### ISSUE TITLE
data type frequency function

### ISSUE THREAD

**Issue by jayesh-07** [jayesh-07/pythonpackage-intelliprocess-DS-5010#2]
Check the data type frequency function and and code such that it is graphically presented

**Comment by sphussey** [comment]
I am trying to handle this for the correlation matrix generation with a numeric_only (bool) argument which will control that. I am just switching to building df.corr() myself

**Comment by sphussey** [comment]
Right now I am extracting only the following dtypes when extracting data from a given dataframe to calculate 
See IntelliViz.pearson_corr_matrix()
`# extract only numerical data types into a new dataframe
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
df2 = df.select_dtypes(include=numerics)`
